---
- name: bind mysql remote address
  ansible.builtin.lineinfile:
    path: /etc/my.cnf
    line: bind-address=0.0.0.0
    create: yes
    state: present
  tags:
  - mysql
  - mysql::changeconfig
  #- always
  notify:
  - restart mysql

- name: Change mysql authentification method
  ansible.builtin.lineinfile:
    path: /etc/my.cnf
    line: default-authentication-plugin=mysql_native_password
    create: yes
    state: present
  tags:
  - mysql
  - mysql::changeconfig
  #- always
  notify:
  - restart mysql

- name: restart mysql
  service:
    name: mysqld
    state: restarted
    enabled: yes
  become: yes
  tags:
  - mysql
  - mysql::changeconfig
